- type: job
  parent: CMJobBase
  id: STTankCrew
  name: stories-job-name-tank-crew
  description: stories-job-description-tank-crew
  playTimeTracker: STJobTankCrew
  requirements:
  - !type:DepartmentTimeRequirement
    department: CMSquad
    time: 36000 # 10 hours
  - !type:RoleTimeRequirement
    role: CMJobCombatTech
    time: 7200 # 2 hour
  startingGear: STGearTankCrew
  icon: "STJobIconDCC"
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-aso
  accessGroups:
  - STTankCrew
  ranks:
    RMCRankCorporal: []
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillVehicles: 3
        RMCSkillLeadership: 3
        RMCSkillOverwatch: 1
        RMCSkillPowerLoader: 2
        RMCSkillEngineer: 2
        RMCSkillFireman: 1
        RMCSkillJtac: 3
        RMCSkillFirearms: 1
        RMCSkillEndurance: 1
    - type: CMVendorUser
      id: STTankCrew
      points: 45
    - type: JobPrefix
      prefix: stories-job-prefix-tank-crew
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: vc
      background:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: background_intel

- type: startingGear
  id: STGearTankCrew
  equipment:
    jumpsuit: CMJumpsuitMarineTanker
    shoes: CMBootsBlackFilled
    id: STIDCardTankCrew
    ears: CMHeadsetPilot

- type: entity
  parent: CMSpawnPointJobBase
  id: STSpawnPointTankCrew
  name: tank crew spawn point
  components:
  - type: SpawnPoint
    job_id: STTankCrew
  - type: Sprite
    sprite: _Stories/Markers/landmarks.rsi
    state: vc_spawn

- type: playTimeTracker
  id: STJobTankCrew
  isHumanoid: true
