- type: job
  parent: CMJobSquadBase
  id: CMCadet
  name: cm-job-name-cadet
  description: cm-job-description-cadet
  playTimeTracker: CMJobCadet
  requirements:
  - !type:DepartmentTimeRequirement
    department: CMSquad
    time: 3600 # 1 hours
    inverted: true
  startingGear: CMGearCadet
  icon: "CMJobIconEmpty"
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-sl
  accessGroups:
  - Rifleman
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillFirearms: 1
    - type: CMVendorUser
      points: 45
    - type: CadetWhitelist
  hasIcon: false

- type: startingGear
  id: CMGearCadet
  equipment:
    back: CMSatchelMarine
    id: CMDogtagCadet

- type: startingGear
  id: CMGearCadetEquipped
  equipment:
    jumpsuit: JumpsuitMarine
    back: CMSatchelMarine
    shoes: CMBootsBlackFilled
    head: ArmorHelmetM10
    outerClothing: CMArmorM3Medium
    gloves: CMHandsBlackMarine
    id: CMDogtagCadet
    ears: CMHeadsetAlpha

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointCadet
  name: cadet spawn point
  components:
  - type: SpawnPoint
    job_id: CMCadet
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: rifleman

- type: playTimeTracker
  id: CMJobCadet
