- type: rank
  id: RMCRankSergeantMajor
  name: Сержант-Майор
  prefix: Серж.-Майор
  paygrade: E9E

- type: rank
  id: RMCRankMasterGunnerySergeant
  name: Главный Сержант Артиллерист
  prefix: Гл. Серж. Арт.
  paygrade: E9

- type: rank
  id: RMCRankFirstSergeant
  name: Первый Сержант
  prefix: 1-й Сержант
  paygrade: E8E

- type: rank
  id: RMCRankMasterSergeant
  name: Главный Сержант
  prefix: Гл. Сержант
  paygrade: E8

- type: rank
  id: RMCRankGunnerySergeant
  name: Сержант Артиллерист
  prefix: Серж. Арт.
  paygrade: E7

- type: rank
  id: RMCRankStaffSergeant
  name: Штаб-Сержант
  prefix: Штаб-Серж.
  paygrade: E6

- type: rank
  id: RMCRankSergeant
  name: Сержант
  prefix: Серж.
  paygrade: E5

- type: rank
  id: RMCRankCorporal
  name: Капрал
  prefix: Капрал
  paygrade: E4

- type: rank
  id: RMCRankLanceCorporal
  name: Младший Капрал
  prefix: Мл. Капрал
  paygrade: E3

- type: rank
  id: RMCRankPrivateFirstClass
  name: Рядовой Первого Класса
  prefix: Ряд. 1-го Кл.
  paygrade: E2

- type: rank
  id: RMCRankPrivate
  name: Рядовой
  prefix: Ряд.
  paygrade: E1

- type: rank
  id: RMCRankRecruit
  name: Recruit
  prefix: Rct.
  paygrade: E0
