# МеталСидж
- type: rank
  id: RMCRankProvostSectorMarshal
  name: Секторальный Маршал
  prefix: Сек. Маршал
  paygrade: O9

# Любой администратор с высоким пониманием закона
- type: rank
  id: RMCRankProvostSeniorMarshal
  name: Старший Маршал
  prefix: Ст. Маршал
  paygrade: O8

# Любой администратор с низким пониманием закона, или что хочет ранг пониже
- type: rank
  id: RMCRankProvostMarshal
  name: Маршал
  prefix: Маршал
  paygrade: O7

# Любой Вайтлист КО
- type: rank
  id: RMCRankProvostDeputyMarshal
  name: Заместитель Маршала
  prefix: Зам. Маршала
  paygrade: O6

# Any player with high law understanding
- type: rank
  id: RMCRankProvostChiefInspector
  name: Chief Inspector
  prefix: PvCI.
  paygrade: O5

# Любой игрок со средне-низким пониманием закона
- type: rank
  id: RMCRankProvostInspector
  name: Provost Inspector
  prefix: PvI.
  paygrade: O4

# Fax responder
- type: rank
  id: RMCRankProvostCommunicationsOfficer
  name: Communications Officer
  prefix: ComOff.
  paygrade: O2

# Любой игрок с низким пониманием закона, с доп. помощью
- type: rank
  id: RMCRankProvostAdvisor
  name: Сержант Майор
  prefix: Серж. Майор
  paygrade: E9E

# Любой игрок с определенной целью, возможно лидер группы
- type: rank
  id: RMCRankProvostProvostTeamLeader
  name: Мастер Сержант
  prefix: Маст. Серж.
  paygrade: E8

# Любой игрок с определенной целью, член группы
- type: rank
  id: RMCRankProvostProvostEnforcer
  name: Старший Сержант
  prefix: Ст. Серж.
  paygrade: E6
