# Базовая предустановка конфигурации, используемая на всех серверах Stories Colonial Marines.
# Загружается перед настройками конфигурации, специфичными для сервера.

[game]
hostname         = "📚 Space Stories - Colonial Marines 🌍 [TTS]"
desc             = ""
lobbyenabled     = true
lobbyduration    = 300
soft_max_players = 200
map_pool         = "CMDefaultMapPool"

[shuttle]
auto_call_time = 0
emergency      = false
preload_grids  = false

[ghost]
kill_crit = false
role_time = 0

[ic]
flavor_text = true
enable_suicide = false

[viewport]
maximum_width = 26

[net]
tickrate        = 60
max_connections = 1024

[vote]
restart_required_ratio = 0.7

[netres]
limit = 10.0

[admin]
new_player_threshold = 600

[autovote]
enabled = false

[atmos]
space_wind           = false
monstermos_rip_tiles = false
grid_impulse         = false

[physics]
maxlinvelocity = 51

[infolinks]
bug_report = "https://discord.gg/5j3WhYanuQ"
discord    = "https://discord.gg/5j3WhYanuQ"
# patreon    = "" Ссылка на бусти
wiki       = "https://spacestories.club/index.php?title=Colonial_Marines"
appeal     = "https://discord.gg/5j3WhYanuQ"
patreon    = "https://discord.gg/5j3WhYanuQ"

# [server]
# rules_file = "CM_Rules.txt"
# rules_header = "ui-rules-header-colonial-marines"

# Оптимизция

[gateway]
generator_enabled = false

[procgen]
preload = false

[rmc]
planet_maps = "/Maps/_RMC14/lv624.yml,/Maps/_RMC14/solaris.yml,/Maps/_RMC14/prison.yml,/Maps/_RMC14/shiva.yml"
